# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-06-24 11:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instagram', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='image',
            name='likes',
        ),
    ]
